apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ott-app
    role: production
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "ott-app"
    tags.datadoghq.com/version: "1.0.0"
  name: production-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      role: production
  template:
    metadata:
      labels:
        role: production
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "ott-app"
        tags.datadoghq.com/version: "1.0.0"
    spec:
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - production
      volumes:
        - name: ott-app
          secret:
            secretName: ott-app-config # kubectl create secret generic ott-app-config --from-file=.env
      containers:
        - name: ott-app
          image: how0326/ott_service:modify
          command: [ "sh", "-c" ]
          args:
            - while true; do
              if [[ -e /app/.env ]]; then
              echo -en '\n\n'; cat /app/.env; fi; node app.js;
              sleep 1;
              done;
          volumeMounts:
            - name: ott-app
              mountPath: /app/.env
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_LOGS_INJECTION
              value: "true"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
#            failureThreshold: 5
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 20
#            periodSeconds: 10
#            successThreshold: 1
#            failureThreshold: 5
#            timeoutSeconds: 20